config/routes.rb
ZWSystemTestow::Application.routes.draw do
  resources :kurses

  resources :podejscies

  resources :kurs

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :tests

  resources :pytanies

  resources :odpowiedzs

  resources :users
  resources :sessions

end

app/models/odpowiedz.rb
class Odpowiedz < ActiveRecord::Base
  belongs_to :pytanie
end

app/controllers/odpowiedzs_controller.rb
class OdpowiedzsController < ApplicationController
  # GET /odpowiedzs
  # GET /odpowiedzs.json
  def index
    @odpowiedzs = Odpowiedz.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @odpowiedzs }
    end
  end

  # GET /odpowiedzs/1
  # GET /odpowiedzs/1.json
  def show
    @odpowiedz = Odpowiedz.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @odpowiedz }
    end
  end

  # GET /odpowiedzs/new
  # GET /odpowiedzs/new.json
  def new
    @odpowiedz = Odpowiedz.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @odpowiedz }
    end
  end

  # GET /odpowiedzs/1/edit
  def edit
    @odpowiedz = Odpowiedz.find(params[:id])
  end

  # POST /odpowiedzs
  # POST /odpowiedzs.json
  def create
    @odpowiedz = Odpowiedz.new(params[:odpowiedz])

    respond_to do |format|
      if @odpowiedz.save
        format.html { redirect_to @odpowiedz, notice: 'Odpowiedz was successfully created.' }
        format.json { render json: @odpowiedz, status: :created, location: @odpowiedz }
      else
        format.html { render action: "new" }
        format.json { render json: @odpowiedz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /odpowiedzs/1
  # PUT /odpowiedzs/1.json
  def update
    @odpowiedz = Odpowiedz.find(params[:id])

    respond_to do |format|
      if @odpowiedz.update_attributes(params[:odpowiedz])
        format.html { redirect_to @odpowiedz, notice: 'Odpowiedz was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @odpowiedz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /odpowiedzs/1
  # DELETE /odpowiedzs/1.json
  def destroy
    @odpowiedz = Odpowiedz.find(params[:id])
    @odpowiedz.destroy

    respond_to do |format|
      format.html { redirect_to odpowiedzs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/odpowiedzs_helper.rb
module OdpowiedzsHelper
end

app/views/odpowiedzs/_form.html.erb
<%= form_for(@odpowiedz) do |f| %>
  <% if @odpowiedz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@odpowiedz.errors.count, "error") %> prohibited this odpowiedz from being saved:</h2>

      <ul>
      <% @odpowiedz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/odpowiedzs/edit.html.erb
<h1>Editing odpowiedz</h1>

<%= render 'form' %>

<%= link_to 'Show', @odpowiedz %> |
<%= link_to 'Back', odpowiedzs_path %>

app/views/odpowiedzs/index.html.erb
<h1>Listing odpowiedzs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @odpowiedzs.each do |odpowiedz| %>
  <tr>
    <td><%= link_to 'Show', odpowiedz %></td>
    <td><%= link_to 'Edit', edit_odpowiedz_path(odpowiedz) %></td>
    <td><%= link_to 'Destroy', odpowiedz, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Odpowiedz', new_odpowiedz_path %>

app/views/odpowiedzs/new.html.erb
<h1>New odpowiedz</h1>

<%= render 'form' %>

<%= link_to 'Back', odpowiedzs_path %>

app/views/odpowiedzs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_odpowiedz_path(@odpowiedz) %> |
<%= link_to 'Back', odpowiedzs_path %>