config/routes.rb
ZWSystemTestow::Application.routes.draw do
  resources :kurses

  resources :podejscies

  resources :kurs

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :tests

  resources :pytanies

  resources :odpowiedzs

  resources :users
  resources :sessions

end

app/models/kurs.rb
class Kurs < ActiveRecord::Base
  #asocjacje
  # z users
  has_many :user_kurses
  has_many :users, :through => :user_kurses
  
  # z testami
  has_many :kurs_tests
  has_many :tests, :through => :kurs_tests
end

app/controllers/kurs_controller.rb
class KursController < ApplicationController
  # GET /kurs
  # GET /kurs.json
  def index
    @kurs = Kur.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kurs }
    end
  end

  # GET /kurs/1
  # GET /kurs/1.json
  def show
    @kur = Kur.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kur }
    end
  end

  # GET /kurs/new
  # GET /kurs/new.json
  def new
    @kur = Kur.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kur }
    end
  end

  # GET /kurs/1/edit
  def edit
    @kur = Kur.find(params[:id])
  end

  # POST /kurs
  # POST /kurs.json
  def create
    @kur = Kur.new(params[:kur])

    respond_to do |format|
      if @kur.save
        format.html { redirect_to @kur, notice: 'Kur was successfully created.' }
        format.json { render json: @kur, status: :created, location: @kur }
      else
        format.html { render action: "new" }
        format.json { render json: @kur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kurs/1
  # PUT /kurs/1.json
  def update
    @kur = Kur.find(params[:id])

    respond_to do |format|
      if @kur.update_attributes(params[:kur])
        format.html { redirect_to @kur, notice: 'Kur was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kurs/1
  # DELETE /kurs/1.json
  def destroy
    @kur = Kur.find(params[:id])
    @kur.destroy

    respond_to do |format|
      format.html { redirect_to kurs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/kurs_helper.rb
module KursHelper
end

app/views/kurs/_form.html.erb
<%= form_for(@kur) do |f| %>
  <% if @kur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kur.errors.count, "error") %> prohibited this kur from being saved:</h2>

      <ul>
      <% @kur.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kurs/edit.html.erb
<h1>Editing kur</h1>

<%= render 'form' %>

<%= link_to 'Show', @kur %> |
<%= link_to 'Back', kurs_path %>

app/views/kurs/index.html.erb
<h1>Listing kurs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kurs.each do |kur| %>
  <tr>
    <td><%= link_to 'Show', kur %></td>
    <td><%= link_to 'Edit', edit_kur_path(kur) %></td>
    <td><%= link_to 'Destroy', kur, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kur', new_kur_path %>

app/views/kurs/new.html.erb
<h1>New kur</h1>

<%= render 'form' %>

<%= link_to 'Back', kurs_path %>

app/views/kurs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_kur_path(@kur) %> |
<%= link_to 'Back', kurs_path %>